# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html

twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
        
fos_ck_editor:
    configs:
        main_config: 
            toolbar:
                - {
                    name: "styles",
                    items: 
                      [
                        "Smiley","-",
                        "TextColor",
                        "BGColor","-",
                        "Bold",
                        "Italic",
                        "Underline",
                        # "Strike",
                        "CodeSnippet", 
                        "Code",
                        "Blockquote",
                        "-",
                        # "Link",
                        # "-",
                        "RemoveFormat",
                        # "-",
                        "Outdent",
                        "Indent",
                        # "-",
                        "-",
                        "JustifyLeft",
                        "JustifyCenter",
                        "JustifyRight",
                        "JustifyBlock",
                        # "Image",
                        "-",
                        "HorizontalRule",
                        "-",
                        "Styles",
                        "Format", 
                        "FontSize", 
                        "Source","-",
                        'Maximize',
                        

                        ]
                    }